# .gitlab-ci.yml

image: python:3.9
services:
  - postgres:13

stages:
  - lint
  - test

variables:
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  POSTGRES_HOST_AUTH_METHOD: trust
  DEBUG: "True"

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

lint:
  stage: lint
  script:
    - black --check .
  after_script:
    - echo " Lint Done"

test:
  stage: test
  script:
    - python manage.py makemigrations buildings members userlog
    - python manage.py migrate
    - python manage.py test
  after_script:
    - echo " Test Done"