version: '3.8'

services:
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DEBUG: ${DEBUG}
    restart: always
    networks:
      - main
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - main
  
  web:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app:rw
      - static:/www/app/staticfiles:rw
      - media:/www/app/media:rw
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DJANGO_NAME: ${POSTGRES_DB}
      DJANGO_USER: ${POSTGRES_USER}
      DJANGO_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_HOST: ${POSTGRES_HOST}

    restart: always
    networks:
      - main
  
  nginx:
    container_name: nginx_ims
    build:
      context: ./nginx/
    volumes:
      - static:/home/app/staticfiles:rw
      - media:/home/app/media:rw
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web
    restart: always
    networks:
      - main
  
  huey:
    container_name: huey
    build:
      context: .
      dockerfile: ./huey/Dockerfile
    volumes:
      - .:/usr/app
    depends_on:
      - redis
    environment:
      DJANGO_NAME: ${POSTGRES_DB}
      DJANGO_USER: ${POSTGRES_USER}
      DJANGO_PASSWORD: ${POSTGRES_PASSWORD}
    command: python manage.py run_huey
    restart: always
    networks:
      - main

  
volumes:
  db_data:
  static:
  media:
networks:
  main: