version: '3.8'

services:
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    networks:
      - main
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - main
  
  web:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DJANGO_NAME: ${DJANGO_NAME}
      DJANGO_USER: ${DJANGO_USER}
      DJANGO_PASSWORD: ${DJANGO_PASSWORD}

    restart: always
    networks:
      - main
  
  huey:
    container_name: huey
    build:
      context: .
      dockerfile: ./huey/Dockerfile
    volumes:
      - .:/usr/app
    depends_on:
      - redis
    environment:
      DJANGO_NAME: ${DJANGO_NAME}
      DJANGO_USER: ${DJANGO_USER}
      DJANGO_PASSWORD: ${DJANGO_PASSWORD}
    command: python manage.py run_huey
    restart: always
    networks:
      - main

  
volumes:
  db_data:
networks:
  main: